create or replace PROCEDURE UPD_ESTADO 
(IDESTADO IN ESTADO.id_estado%TYPE,
ESTAD in ESTADO.ESTADO%TYPE 
,DESCRIPCION in ESTADO.DESCRIPCION_ESTADO%TYPE  
,CODIGO in ESTADO.COD_ESTADO%TYPE  
)AS
BEGIN
UPDATE  VENTAS.ESTADO ES  SET  ES.ESTADO=ESTAD,
ES.DESCRIPCION_ESTADO=DESCRIPCION,
ES.COD_ESTADO=CODIGO
WHERE id_estado=IDESTADO; 
END UPD_ESTADO;

create or replace PROCEDURE UPD_ROL
(IDROL IN ROL.ID_ROL%TYPE,
TIPO IN ROL.TIPO_ROL%TYPE
,DESCRIP IN ROL.DESCRIPCION_ROL%TYPE
,CODIGO IN ROL.COD_ROL%TYPE
)AS
BEGIN 
UPDATE VENTAS.ROL RL SET RL.TIPO_ROL=TIPO,RL.DESCRIPCION_ROL=DESCRIP,
RL.COD_ROL=CODIGO WHERE RL.ID_ROL=IDROL;
END UPD_ROL;

create or replace PROCEDURE UPD_DEPARTAMENTO
(IDDEPARTAMENTO IN DEPARTAMENTO.id_departamento%TYPE,
NOMBREDPT IN DEPARTAMENTO.NOMBRE_DEPARTAMENTO%TYPE)AS
BEGIN
UPDATE  VENTAS.DEPARTAMENTO DPT SET DPT.NOMBRE_DEPARTAMENTO= NOMBREDPT
WHERE DPT.ID_DEPARTAMENTO=IDDEPARTAMENTO;
END UPD_DEPARTAMENTO;

create or replace PROCEDURE UPD_MUNICIPIOS
(IDMUNICIPIO IN MUNICIPIOS.id_municipios%TYPE,
NOMBREMU IN MUNICIPIOS.NOMBRE_MUNICIPIOS%TYPE,
IDDEPARTAMENTO IN MUNICIPIOS.ID_DEPARTAMENTO_MUNICIPIO%TYPE)AS
BEGIN 
UPDATE  VENTAS.MUNICIPIOS MU SET MU.NOMBRE_MUNICIPIOS=NOMBREMU,
MU.ID_DEPARTAMENTO_MUNICIPIO= IDDEPARTAMENTO WHERE MU.ID_MUNICIPIOS=IDMUNICIPIO; 
END UPD_MUNICIPIOS;

create or replace PROCEDURE UPD_CATEGORIA
(IDCATEGORIA IN CATEGORIA.id_categoria%TYPE,
NOMBRECA IN CATEGORIA.NOMBRE_CATEGORIA%TYPE,
DESCRIPCIONCA IN CATEGORIA.DESCRIPCION_CATEGORIA%TYPE,
CODIGOCA IN CATEGORIA.CODIGO_CATEGORIA%TYPE )AS
BEGIN
UPDATE  VENTAS.CATEGORIA CA SET
CA.NOMBRE_CATEGORIA=NOMBRECA,CA.DESCRIPCION_CATEGORIA=DESCRIPCIONCA,CA.CODIGO_CATEGORIA=CODIGOCA
WHERE CA.ID_CATEGORIA=IDCATEGORIA;
END UPD_CATEGORIA;

create or replace PROCEDURE UPD_DIRECCIONES
(IDDIRECCION IN DIRECCIONES.id_direccion%TYPE,
DIRECC IN DIRECCIONES.DIRECCION%TYPE,
IDMUNICIPIO IN DIRECCIONES.ID_MUNICIPIO_DIRECCION%TYPE)AS
BEGIN 
UPDATE VENTAS.DIRECCIONES DI SET
DI.DIRECCION=DIRECC,DI.ID_MUNICIPIO_DIRECCION=IDMUNICIPIO 
WHERE DI.ID_DIRECCION=IDDIRECCION;
END UPD_DIRECCIONES;


create or replace PROCEDURE UPD_PROVEEDOR
(IDPROVEEDOR IN PROVEEDOR.ID_PROVEEDOR%TYPE,
NOMBREPROVE IN PROVEEDOR.NOMBRE_PROVEEDOR%TYPE,
NIT IN PROVEEDOR.NIT_PROVEEDOR%TYPE,
TELEFONOPROVE IN PROVEEDOR.TELEFONO_PROVEEDOR%TYPE,
IDCATEGORIAPROVE IN PROVEEDOR.ID_CATEGORIA_PROVEEDOR%TYPE,
IDESTADOPROVE IN PROVEEDOR.ID_ESTADO_PROVEEDOR%TYPE,
IDDIRECCIONPROVE IN PROVEEDOR.ID_DIRECCION_PROVEEDOR%TYPE
)AS
BEGIN 
UPDATE  VENTAS.PROVEEDOR PV SET PV.NOMBRE_PROVEEDOR=NOMBREPROVE,PV.NIT_PROVEEDOR=NIT,
PV.TELEFONO_PROVEEDOR=TELEFONOPROVE,PV.ID_CATEGORIA_PROVEEDOR=IDCATEGORIAPROVE,
PV.ID_ESTADO_PROVEEDOR=IDESTADOPROVE,PV.ID_DIRECCION_PROVEEDOR=IDDIRECCIONPROVE
WHERE PV.ID_PROVEEDOR=IDPROVEEDOR;
END UPD_PROVEEDOR;

create or replace PROCEDURE UPD_PERSONA
(IDPERSONA IN PERSONA.ID_PERSONA%TYPE,
NOMBRE1 IN PERSONA.PRIMER_NOMBRE%TYPE,
NOMBRE2 IN PERSONA.SEGUNDO_NOMBRE%TYPE,
APELLIDO1 IN PERSONA.PRIMER_APELLIDO%TYPE,
APELLIDO2 IN PERSONA.SEGUNDO_APELLIDO%TYPE,
CORREO IN PERSONA.EMAIL%TYPE,
EDADPE IN PERSONA.EDAD%TYPE,
GENEROPE IN PERSONA.GENERO%TYPE,
TELEFONOPE IN PERSONA.TELEFONO_PERSONA%TYPE,
IDDIRECCIONPE IN PERSONA.ID_DIRECCION_PERSONA%TYPE
)AS
BEGIN
UPDATE  VENTAS.PERSONA PE SET PE.PRIMER_NOMBRE=NOMBRE1,PE.SEGUNDO_NOMBRE=NOMBRE2,
PE.PRIMER_APELLIDO=APELLIDO1,PE.SEGUNDO_APELLIDO=APELLIDO2,PE.EMAIL=CORREO,PE.EDAD=EDADPE,
PE.GENERO=GENEROPE,PE.TELEFONO_PERSONA=TELEFONOPE,PE.ID_DIRECCION_PERSONA=IDDIRECCIONPE
WHERE PE.ID_PERSONA=IDPERSONA;
END UPD_PERSONA;


create or replace PROCEDURE UPD_USUARIOS
(IDUSUARIO IN USUARIOS.ID_USUARIO%TYPE,
NOMBREUSU IN USUARIOS.NOMBRE_USUARIO%TYPE,
CLAVEUSU IN USUARIOS.CLAVE_USUARIO%TYPE,
IDESTADOUSU IN USUARIOS.ID_ESTADO_USUARIO%TYPE,
IDPERSONAUSU IN USUARIOS.ID_PERSONA_USUARIO%TYPE,
IDROLUSU IN USUARIOS.ID_ROL_USUARIO%TYPE
)AS
BEGIN
UPDATE VENTAS.USUARIOS US SET US.NOMBRE_USUARIO=NOMBREUSU,US.CLAVE_USUARIO=CLAVEUSU,
US.ID_ESTADO_USUARIO=IDESTADOUSU,US.ID_PERSONA_USUARIO=IDPERSONAUSU,US.ID_ROL_USUARIO=IDROLUSU
WHERE US.ID_USUARIO=IDUSUARIO;
END UPD_USUARIOS;

create or replace PROCEDURE UPD_ARTICULOS
(IDARTICULO IN ARTICULOS.ID_ARTICULO%TYPE,
NOMBRE_ART IN ARTICULOS.NOMBRE_ARTICULO%TYPE,
PRECIO_ART IN ARTICULOS.PRECIO_ARTICULO%TYPE,
IMAGEN_ART IN ARTICULOS.IMAGEN_ARTICULO%TYPE,
IDCATEGORIA_ART IN ARTICULOS.ID_CATEGORIA_ARTICULO%TYPE,
IDPROVEEDOR_ART IN ARTICULOS.ID_PROVEEDOR_ARTICULO%TYPE
)AS
BEGIN
UPDATE VENTAS.ARTICULOS AR SET AR.NOMBRE_ARTICULO=NOMBRE_ART,AR.PRECIO_ARTICULO=PRECIO_ART,
AR.IMAGEN_ARTICULO=IMAGEN_ART,AR.ID_CATEGORIA_ARTICULO=IDCATEGORIA_ART,AR.ID_PROVEEDOR_ARTICULO=IDPROVEEDOR_ART
WHERE AR.ID_ARTICULO=IDARTICULO;
END UPD_ARTICULOS;

create or replace PROCEDURE UPD_TIPOPAGO
(IDTIPOPAGO IN TIPO_PAGO.ID_TIPO_PAGO%TYPE,
PAGOTIPO IN TIPO_PAGO.TIPO_PAGO%TYPE)AS
BEGIN
UPDATE VENTAS.TIPO_PAGO TP SET TP.TIPO_PAGO=PAGOTIPO WHERE TP.ID_TIPO_PAGO=IDTIPOPAGO;
END UPD_TIPOPAGO;

create or replace PROCEDURE UPD_TIPODOCUEMNTO
(IDDOCUMENTO IN TIPO_DOCUMENTO.ID_DOCUMENTO%TYPE,
NOMBREDC IN TIPO_DOCUMENTO.NOMBRE_DOCUMENTO%TYPE)AS
BEGIN
UPDATE VENTAS.TIPO_DOCUMENTO DC SET DC.NOMBRE_DOCUMENTO=NOMBREDC WHERE DC.ID_DOCUMENTO=IDDOCUMENTO; 
END UPD_TIPODOCUEMNTO

create or replace PROCEDURE UPD_PEDIDOS
(IDPEDIDO IN PEDIDO.ID_PEDIDO%TYPE,
FECHAPEDIDO IN PEDIDO.FECHA_PEDIDO%TYPE,
FECHAENVIO IN PEDIDO.FECHA_ENVIO%TYPE,
MONTO IN PEDIDO.MONTO_TOTAL%TYPE,
IDESTADO IN PEDIDO.ID_ESTADO_PEDIDO%TYPE,
IDUSUARIO IN PEDIDO.ID_USUARIO_PEDIDO%TYPE,
IDTIPOPAGO IN PEDIDO.ID_TIPOPAGO_PEDIDO%TYPE,
IDDOCUEMTO IN PEDIDO.ID_DOCUMENTO_PEDIDO%TYPE)AS
BEGIN
UPDATE  VENTAS.PEDIDO PE SET PE.FECHA_PEDIDO=FECHAPEDIDO,PE.FECHA_ENVIO=FECHAENVIO,
PE.MONTO_TOTAL=MONTO,PE.ID_ESTADO_PEDIDO=IDESTADO,PE.ID_USUARIO_PEDIDO=IDUSUARIO,
PE.ID_TIPOPAGO_PEDIDO=IDTIPOPAGO,PE.ID_DOCUMENTO_PEDIDO=IDDOCUEMTO
WHERE PE.ID_PEDIDO=IDPEDIDO;
END UPD_PEDIDOS;

create or replace PROCEDURE UPD_DETALLEPEDIDO
(IDDETALLEPEDIDO IN DETALLE_PEDIDO.ID_PEDIDO_DETALLE%TYPE,
IDARTICULO IN DETALLE_PEDIDO.ID_ARTICULO_DETALLE%TYPE,
CANTIDAD_DE IN DETALLE_PEDIDO.CANTIDAD%TYPE,
TOTALARTICULO IN DETALLE_PEDIDO.TOTAL_ARTICULO%TYPE)AS
BEGIN 
UPDATE VENTAS.DETALLE_PEDIDO DE SET DE.ID_ARTICULO_DETALLE=IDARTICULO,
DE.CANTIDAD=CANTIDAD_DE,DE.TOTAL_ARTICULO=TOTALARTICULO
WHERE DE.ID_PEDIDO_DETALLE=IDDETALLEPEDIDO;
END UPD_DETALLEPEDIDO;