CREATE SEQUENCE SE_ESTADO START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_ESTADO
BEFORE INSERT ON ESTADO
FOR EACH ROW
BEGIN 
SELECT SE_ESTADO.NEXTVAL INTO :NEW.id_estado FROM DUAL; 
END;

CREATE SEQUENCE SE_ROL START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_ROL
BEFORE INSERT ON  ROL
FOR EACH ROW
BEGIN 
SELECT SE_ROL.NEXTVAL INTO :NEW.id_rol FROM DUAL;
END;

CREATE SEQUENCE SE_DEPARTAMENTO START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_DEPARTAMENTO
BEFORE INSERT ON DEPARTAMENTO
FOR EACH ROW
BEGIN 
SELECT SE_DEPARTAMENTO.NEXTVAL INTO :NEW.id_departamento FROM DUAL;
END;

CREATE SEQUENCE SE_MUNICIPIO START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_MUNICIPIO
BEFORE INSERT ON MUNICIPIOS
FOR EACH ROW
BEGIN 
SELECT SE_MUNICIPIO.NEXTVAL INTO :NEW.id_municipios FROM DUAL;
END;

CREATE SEQUENCE SE_CATEGORIA START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_CATEGORIA
BEFORE INSERT ON  CATEGORIA
FOR EACH ROW
BEGIN 
SELECT SE_CATEGORIA.NEXTVAL INTO :NEW.id_categoria FROM DUAL;
END;

CREATE SEQUENCE SE_DIRECCIONES START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_DIRECCION
BEFORE INSERT ON DIRECCIONES
BEGIN 
SELECT SE_DIRECCIONES.NEXTVAL INTO :NEW.id_direccion FROM DUAL;  
END;

CREATE SEQUENCE SE_PROVEEDOR START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_PROVEEDOR
BEFORE INSERT ON PROVEEDOR
BEGIN 
SELECT SE_PROVEEDOR.NEXTVAL INTO :NEW.id_proveedor FROM DUAL;
END;

CREATE SEQUENCE SE_PERSONA START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_PERSONA
BEFORE INSERT ON PERSONA
BEGIN 
SELECT SE_PERSONA.NEXTVAL INTO :NEW.id_persona FROM DUAL;
END;

CREATE SEQUENCE SE_USUARIOS START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_USUARIO
BEFORE INSERT ON USUARIOS
BEGIN
SELECT SE_USUARIOS.NEXTVAL INTO :NEW.id_usuario FROM DUAL;
END;

CREATE SEQUENCE SE_ARTICULOS START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_ARTICULOS
BEFORE INSERT ON ARTICULOS
BEGIN 
SELECT SE_ARTICULOS.NEXTVAL INTO :NEW.id_articulo FROM DUAL;
END;

CREATE SEQUENCE SE_TIPOPAGO START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_TIPOPAGO
BEFORE INSERT ON TIPO_PAGO
BEGIN 
SELECT SE_TIPOPAGO.NEXTVAL INTO :NEW.id_tipo_pago FROM DUAL;
END;

CREATE SEQUENCE SE_TIPODOCUMENTO START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_TIPODOCUMENTO
BEFORE INSERT ON TIPO_DOCUMENTO
BEGIN 
SELECT SE_TIPODOCUMENTO.NEXTVAL INTO :NEW.id_documento FROM DUAL;
END;

CREATE SEQUENCE SE_PEDIDO START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_PEDIDO
BEFORE INSERT ON PEDIDO
BEGIN 
SELECT SE_PEDIDO.NEXTVAL INTO :NEW.id_pedido FROM DUAL; 
END;

CREATE SEQUENCE SE_DETALLEPEDIDO START WITH 1 INCREMENT BY 1 ORDER;
CREATE OR REPLACE TRIGGER TT_DETALLEPEDIDO
BEFORE INSERT ON DETALLE_PEDIDO
BEGIN 
SELECT SE_DETALLEPEDIDO.NEXTVAL INTO :NEW.id_pedido_detalle FROM DUAL;
END;
