CREATE OR REPLACE VIEW VW_DEPARTAMENTOS 
AS SELECT DP.ID_DEPARTAMENTO AS CODIGO,DP.NOMBRE_DEPARTAMENTO AS NOMBRE FROM DEPARTAMENTO DP;

CREATE OR REPLACE VIEW VW_CATE_ARTICULOS AS SELECT C.ID_CATEGORIA AS codigo, C.NOMBRE_CATEGORIA AS nombre  
FROM CATEGORIA C WHERE C.CODIGO_CATEGORIA='PRD';

CREATE OR REPLACE VIEW VW_CATE_SERVICIOS AS SELECT C.ID_CATEGORIA AS codigo, C.NOMBRE_CATEGORIA AS nombre  
FROM CATEGORIA C WHERE C.CODIGO_CATEGORIA='SE';