CREATE OR REPLACE VIEW VW_DEPARTAMENTOS 
AS SELECT DP.ID_DEPARTAMENTO AS CODIGO,DP.NOMBRE_DEPARTAMENTO AS NOMBRE FROM DEPARTAMENTO DP;

CREATE OR REPLACE VIEW VW_CATE_ARTICULOS AS SELECT C.ID_CATEGORIA AS codigo, C.NOMBRE_CATEGORIA AS nombre  
FROM CATEGORIA C WHERE C.CODIGO_CATEGORIA='PRD';

CREATE OR REPLACE VIEW VW_CATE_SERVICIOS AS SELECT C.ID_CATEGORIA AS codigo, C.NOMBRE_CATEGORIA AS nombre  
FROM CATEGORIA C WHERE C.CODIGO_CATEGORIA='SE';

CREATE OR REPLACE VIEW VW_CATEGORIAS AS SELECT C.ID_CATEGORIA AS ID,C.CODIGO_CATEGORIA AS CODIGO,C.NOMBRE_CATEGORIA AS NOMBRE,
C.DESCRIPCION_CATEGORIA AS DESCRIPCION
FROM CATEGORIA C;

CREATE OR REPLACE VIEW VW_PRODUCTOS AS SELECT A.ID_ARTICULO AS CODIGO,A.IMAGEN_ARTICULO AS IMAGEN,A.NOMBRE_ARTICULO AS NOMBRE,
A.PRECIO_ARTICULO AS PRECIO,A.DESCRIPCION_ARTICULO AS DESCIPCION,C.ID_CATEGORIA AS CATEGORIA
FROM ARTICULOS A INNER JOIN CATEGORIA C ON C.ID_CATEGORIA=A.ID_CATEGORIA_ARTICULO;

CREATE OR REPLACE VIEW VW_SERVICIOS AS SELECT S.ID_SERVICIO AS CODIGO,S.IMAGEN_SERVICIO AS IMAGEN,S.NOMBRE_SERVICIO AS NOMBRE,
S.PRECIO_SERVICIO AS PRECIO,S.DESCRIPCION_SERVICIO AS DESCRIPCION,C.ID_CATEGORIA AS CATEGORIA
FROM SERVICIOS S INNER JOIN CATEGORIA C ON C.ID_CATEGORIA=S.ID_CATEGORIA_SERVICIO;

CREATE OR REPLACE VIEW VW_ROLES AS select r.ID_ROL as CODICO,r.TIPO_ROL AS TIPO,r.DESCRIPCION_ROL AS DESCRIPCION from ROL r;