/*RETOAN MAXIMO DE DIRECCION*/
CREATE OR REPLACE FUNCTION MaxDireccion
  RETURN NUMERIC
IS
  l_max NUMERIC;

BEGIN

SELECT MAX(ID_DIRECCION) AS DD into l_max FROM DIRECCIONES;

  RETURN l_max;
END;


/*RETORNA MAXIMO DE PERSONA*/

CREATE OR REPLACE FUNCTION MaxPersona
  RETURN NUMERIC
IS
  l_max NUMERIC;
  
BEGIN
  
SELECT MAX(ID_PERSONA) AS PP INTO l_max FROM PERSONA;

  RETURN l_max;
END;
