create or replace PROCEDURE SP_IN_DETALLEPEDIDO(idencabezado in DETALLE_PEDIDO.ID_PEDIDO_DETALLE%type,
idarticulo in DETALLE_PEDIDO.ID_ARTICULO_DETALLE%TYPE,cantidad in DETALLE_PEDIDO.CANTIDAD%TYPE,
total in DETALLE_PEDIDO.TOTAL_ARTICULO%TYPE,precio in DETALLE_PEDIDO.PRECIO%type)
AS
 OPTION_NOT_FOUND EXCEPTION;

BEGIN 
savepoint prev;

INSERT INTO DETALLE_PEDIDO (ID_PEDIDO_DETALLE, ID_ARTICULO_DETALLE, CANTIDAD, TOTAL_ARTICULO,PRECIO)
VALUES (idencabezado, idarticulo,cantidad,total,precio);
 APEX_JSON.open_object;
 APEX_JSON.write('Status',200);
 APEX_JSON.close_object;
    COMMIT;
EXCEPTION 
    WHEN OPTION_NOT_FOUND THEN
         HTP.print(SQLERRM);
    WHEN OTHERS THEN
         HTP.print(SQLERRM);
END SP_IN_DETALLEPEDIDO;

EXECUTE SP_IN_DETALLEPEDIDO(24,41,10,50,10);