CREATE OR REPLACE PROCEDURE SP_IN_USUARIO
(DIRE IN DIRECCIONES.DIRECCION%TYPE,IDMUNI IN DIRECCIONES.ID_MUNICIPIO_DIRECCION %TYPE,
PN IN PERSONA.PRIMER_NOMBRE%TYPE,SN IN PERSONA.SEGUNDO_NOMBRE%TYPE,AP1 IN PERSONA.PRIMER_APELLIDO%TYPE,
AP2 IN PERSONA.SEGUNDO_APELLIDO%TYPE,EDAD IN PERSONA.EDAD%TYPE,GENERO IN PERSONA.GENERO%TYPE,TELEFONO IN PERSONA.TELEFONO_PERSONA%TYPE,
USUA IN USUARIOS.NOMBRE_USUARIO%TYPE,CLAVE IN USUARIOS.CLAVE_USUARIO%TYPE,CORREO IN USUARIOS.EMAIL%TYPE)
AS
 OPTION_NOT_FOUND EXCEPTION;
BEGIN 
savepoint prev;
INSERT INTO DIRECCIONES (DIRECCION,ID_MUNICIPIO_DIRECCION) values(DIRE,IDMUNI);

INSERT INTO PERSONA (PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,EDAD,GENERO,TELEFONO_PERSONA,ID_DIRECCION_PERSONA) 
VALUES(PN,SN,AP1,AP2,EDAD,GENERO,TELEFONO,MaxDireccion);

INSERT INTO USUARIOS (NOMBRE_USUARIO,CLAVE_USUARIO,EMAIL,IMAGE_PERFIL,ID_ESTADO_USUARIO,ID_PERSONA_USUARIO,ID_ROL_USUARIO) VALUES(USUA,CLAVE,CORREO,NULL,1,MaxPersona,1);
APEX_JSON.write('status:200');
 
    COMMIT;
EXCEPTION 
    WHEN OPTION_NOT_FOUND THEN
         HTP.print(SQLERRM);
    WHEN OTHERS THEN
         HTP.print(SQLERRM);
END SP_IN_USUARIO;