CREATE OR REPLACE PROCEDURE SP_SL_SERVICIOS
AS
servicios_cursor SYS_REFCURSOR;
respuesta EXCEPTION;
BEGIN
SAVEPOINT prev;
OPEN servicios_cursor FOR

select se.ID_SERVICIO as Codigo,CA.NOMBRE_CATEGORIA AS Categoria,se.DESCRIPCION_SERVICIO as Descripcion
,BASE64ENCODE(se.IMAGEN_SERVICIO) as imagen,
se.NOMBRE_SERVICIO as nombre,se.PRECIO_SERVICIO as precio from  SERVICIOS se 
INNER JOIN CATEGORIA CA ON CA.ID_CATEGORIA=se.ID_CATEGORIA_SERVICIO;

APEX_JSON.write( servicios_cursor);
COMMIT;
EXCEPTION
WHEN respuesta then
    HTP.print(SQLERRM);
    WHEN OTHERS THEN
    HTP.print(SQLERRM);
END SP_SL_SERVICIOS;