create or replace PROCEDURE SP_SL_SERVICIOS
AS
servicios_cursor SYS_REFCURSOR;
respuesta EXCEPTION;
BEGIN
SAVEPOINT prev;
OPEN servicios_cursor FOR

select A.ID_ARTICULO as Codigo,se.DESCRIPCION_SERVICIO as Descripcion
,BASE64ENCODE(se.IMAGEN_SERVICIO) as imagen,
se.NOMBRE_SERVICIO as nombre,se.PRECIO_SERVICIO as precio from  SERVICIOS se
INNER JOIN ARTICULOS A ON A.ID_ARTICULO=se.ID_SERVICIOS_ARTICULOS;

APEX_JSON.write(servicios_cursor);
COMMIT;
EXCEPTION
WHEN respuesta then
    HTP.print(SQLERRM);
    WHEN OTHERS THEN
    HTP.print(SQLERRM);
END SP_SL_SERVICIOS;