CREATE OR REPLACE PROCEDURE SP_SL_PRODUCTOS
AS 
productos_cursor SYS_REFCURSOR;
 OPTION_NOT_FOUND EXCEPTION;
begin 
  savepoint prev;

OPEN productos_cursor FOR
SELECT A.ID_ARTICULO AS Codigo,C.NOMBRE_CATEGORIA AS Categoria,A.DESCRIPCION_ARTICULO AS Descripcion,BASE64ENCODE(A.IMAGEN_ARTICULO) AS Imagen,
A.NOMBRE_ARTICULO AS Nombre,A.PRECIO_ARTICULO AS Precio
FROM ARTICULOS A INNER JOIN CATEGORIA C ON A.ID_CATEGORIA_ARTICULO=C.ID_CATEGORIA;


 APEX_JSON.write(productos_cursor);
 
    COMMIT;
EXCEPTION 
    WHEN OPTION_NOT_FOUND THEN
         HTP.print(SQLERRM);
    WHEN OTHERS THEN
         HTP.print(SQLERRM);
end SP_SL_PRODUCTOS;
