
-- Generated by ORDS REST Data Services 19.4.0.r3521226
-- Schema: POLICOMERCE  Date: Thu Apr 30 12:27:12 2020 
--

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'ventas',
      p_base_path      => '/policomerce/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.SET_MODULE_ORIGINS_ALLOWED( 
      p_module_name     => 'ventas',
      p_origins_allowed => 'tipopago/'); 

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'pedidos/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'pedidos/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin 
SP_SL_PEDIDO(:Id);
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'pedidos/',
      p_method             => 'GET',
      p_name               => 'Id',
      p_bind_variable_name => 'Id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'pedidos/',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_DEL_PEDIDO(:Id);
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'pedidos/',
      p_method             => 'DELETE',
      p_name               => 'Id',
      p_bind_variable_name => 'Id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'servicios/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'servicios/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_SL_SERVICIOS;
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'articulos/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'articulos/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_SL_PRODUCTOS;
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'departamento/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'departamento/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin 
SP_SL_DEPARTAMENTO;
end;
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'login',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'login',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_SL_LOGIN(:Clave,:Usuario);
exception 
when others then
:msg := ''false'';
end;
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'login',
      p_method             => 'POST',
      p_name               => 'USUARIO',
      p_bind_variable_name => 'Usuario',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'login',
      p_method             => 'POST',
      p_name               => 'CLAVE',
      p_bind_variable_name => 'Clave',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'login',
      p_method             => 'POST',
      p_name               => 'MSG',
      p_bind_variable_name => 'msg',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'usuarios/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'usuarios/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
SP_SL_VALIDAR_USUARIO(:USUARIO);
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'GET',
      p_name               => 'USUARIO',
      p_bind_variable_name => 'USUARIO',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'usuarios/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin 
SP_IN_USUARIO(:DIRECCION,:IDMUNICIPIO,:NOMBRE1,:NOMBRE2,:APELLIDO1,:APELLIDO2,:EDAD,:GENERO,:TELEFONO,:USUARIO,:CLAVE,:CORREO);
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'DIRECCION',
      p_bind_variable_name => 'DIRECCION',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'IDMUNICIPIO',
      p_bind_variable_name => 'IDMUNICIPIO',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'NOMBRE1',
      p_bind_variable_name => 'NOMBRE1',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'NOMBRE2',
      p_bind_variable_name => 'NOMBRE2',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'APELLIDO1',
      p_bind_variable_name => 'APELLIDO1',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'APELLIDO2',
      p_bind_variable_name => 'APELLIDO2',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'EDAD',
      p_bind_variable_name => 'EDAD',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'GENERO',
      p_bind_variable_name => 'GENERO',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'TELEFONO',
      p_bind_variable_name => 'TELEFONO',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'USUARIO',
      p_bind_variable_name => 'USUARIO',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'CLAVE',
      p_bind_variable_name => 'CLAVE',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'usuarios/',
      p_method             => 'POST',
      p_name               => 'CORREO',
      p_bind_variable_name => 'CORREO',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'municipios/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'municipios/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_SL_MUNICIPIO(:ID);
end;
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'municipios/',
      p_method             => 'GET',
      p_name               => 'ID',
      p_bind_variable_name => 'ID',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'numpedido/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'numpedido/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_SL_NUMPEDIDO;
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'tipopago/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'tipopago/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_SL_TIPOPAGO;
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'documento/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'documento/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_SL_DOCUMENTO;
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'encabezadopedido/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'encabezadopedido/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin 
SP_SL_IDPEDIDO(:cod);
end; ');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'encabezadopedido/',
      p_method             => 'GET',
      p_name               => 'cod',
      p_bind_variable_name => 'cod',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'encabezadopedido/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_IN_PEDIDOENCABEZADO(:IdUser,:IdTipoPago,:IdTipoDoc,:MontoTotal);
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'encabezadopedido/',
      p_method             => 'POST',
      p_name               => 'IdUser',
      p_bind_variable_name => 'IdUser',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'encabezadopedido/',
      p_method             => 'POST',
      p_name               => 'IdTipoPago',
      p_bind_variable_name => 'IdTipoPago',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'encabezadopedido/',
      p_method             => 'POST',
      p_name               => 'IdTipoDoc',
      p_bind_variable_name => 'IdTipoDoc',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'encabezadopedido/',
      p_method             => 'POST',
      p_name               => 'MontoTotal',
      p_bind_variable_name => 'MontoTotal',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ventas',
      p_pattern        => 'pedidodetalle/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'pedidodetalle/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_SL_PEDIDODETALLE(:Id);
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'pedidodetalle/',
      p_method             => 'GET',
      p_name               => 'Id',
      p_bind_variable_name => 'Id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ventas',
      p_pattern        => 'pedidodetalle/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
SP_IN_DETALLEPEDIDO(:IdEncabezado,:CodigoArticulo,:Cantidad,:TotalArticulo,:Precio);
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'pedidodetalle/',
      p_method             => 'POST',
      p_name               => 'CodigoArticulo',
      p_bind_variable_name => 'CodigoArticulo',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'pedidodetalle/',
      p_method             => 'POST',
      p_name               => 'Cantidad',
      p_bind_variable_name => 'Cantidad',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'pedidodetalle/',
      p_method             => 'POST',
      p_name               => 'IdEncabezado',
      p_bind_variable_name => 'IdEncabezado',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'pedidodetalle/',
      p_method             => 'POST',
      p_name               => 'Precio',
      p_bind_variable_name => 'Precio',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ventas',
      p_pattern            => 'pedidodetalle/',
      p_method             => 'POST',
      p_name               => 'TotalArticulo',
      p_bind_variable_name => 'TotalArticulo',
      p_source_type        => 'HEADER',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => NULL);

    
        
COMMIT;

END;